#!/usr/bin/env php
<?php

$examplesDir = __DIR__.'/examples';
$thenPackage = __DIR__.'/then-package.json';

$address = $argv[1] ?? 'localhost:8080';

echo 'Installing assets...';
passthru("php vendor/bin/then install:assets {$examplesDir} {$thenPackage}");
echo 'OK'.PHP_EOL;

echo "Starting web server on http://{$address}\n";
passthru("php -S {$address} -t {$examplesDir}");